{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "5a795c59-b2f7-4693-a17d-708c6de82468",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Executing: Extract job descriptions from job links.\n",
      "Job descriptions extracted successfully.\n",
      "Executing: Tailor the user’s resume for the job descriptions.\n",
      "Resumes tailored successfully for job descriptions.\n",
      "Executing: Save tailored resumes and job descriptions securely.\n",
      "Resumes and job descriptions saved successfully.\n",
      "Files saved successfully!\n"
     ]
    }
   ],
   "source": [
    "from crewai import Agent, Task, Crew\n",
    "# Import necessary module\n",
    "import os\n",
    "\n",
    "# Define Agents\n",
    "web_scraper_agent = Agent(\n",
    "    role=\"Web Scraper\",\n",
    "    goal=\"Extract detailed job descriptions from job links.\",\n",
    "    backstory=\"Responsible for fetching job descriptions from various platforms.\"\n",
    ")\n",
    "\n",
    "resume_tailoring_agent = Agent(\n",
    "    role=\"Resume Tailoring Specialist\",\n",
    "    goal=\"Customize the user's resume for each job description.\",\n",
    "    backstory=\"Ensure resumes highlight relevant skills and experiences.\"\n",
    ")\n",
    "\n",
    "data_management_agent = Agent(\n",
    "    role=\"Data Management Specialist\",\n",
    "    goal=\"Store tailored resumes and job descriptions securely.\",\n",
    "    backstory=\"Ensure data integrity and security during the storage process.\"\n",
    ")\n",
    "\n",
    "tasks = []\n",
    "\n",
    "# Example input\n",
    "job_links = [\"https://www.linkedin.com/job/sample1\", \"https://www.linkedin.com/job/sample2\"]\n",
    "user_resume = \"path_to_uploaded_resume.docx\"\n",
    "\n",
    "# Define tasks\n",
    "tasks.extend([\n",
    "    Task(\n",
    "        description=\"Extract job descriptions from job links.\",\n",
    "        agent=web_scraper_agent\n",
    "    ),\n",
    "    Task(\n",
    "        description=\"Tailor the user’s resume for the job descriptions.\",\n",
    "        agent=resume_tailoring_agent\n",
    "    ),\n",
    "    Task(\n",
    "        description=\"Save tailored resumes and job descriptions securely.\",\n",
    "        agent=data_management_agent\n",
    "    )\n",
    "])\n",
    "\n",
    "# Simulated execution\n",
    "for task in tasks:\n",
    "    print(f\"Executing: {task.description}\")\n",
    "    if task.agent.role == \"Web Scraper\":\n",
    "        # Simulate job description scraping\n",
    "        print(\"Job descriptions extracted successfully.\")\n",
    "    elif task.agent.role == \"Resume Tailoring Specialist\":\n",
    "        # Simulate resume tailoring\n",
    "        print(\"Resumes tailored successfully for job descriptions.\")\n",
    "    elif task.agent.role == \"Data Management Specialist\":\n",
    "        # Simulate data storage\n",
    "        print(\"Resumes and job descriptions saved successfully.\")\n",
    "\n",
    "# Define the directory for saving files\n",
    "output_directory = r\"C:\\AI_Assistant\\outputs\"\n",
    "os.makedirs(output_directory, exist_ok=True)  # Creates the directory if it doesn’t exist\n",
    "\n",
    "# Example: Save job descriptions\n",
    "extracted_job_descriptions = [\n",
    "    \"Job Description 1: AI Engineer for NLP systems.\",\n",
    "    \"Job Description 2: Data Scientist for predictive modeling.\",\n",
    "]\n",
    "\n",
    "for i, job_description in enumerate(extracted_job_descriptions, start=1):\n",
    "    file_path = os.path.join(output_directory, f\"job_description_{i}.txt\")\n",
    "    with open(file_path, \"w\") as file:\n",
    "        file.write(job_description)\n",
    "\n",
    "# Example: Save tailored resumes\n",
    "tailored_resumes = [\n",
    "    \"Resume 1 tailored for AI Engineer position.\",\n",
    "    \"Resume 2 tailored for Data Scientist position.\",\n",
    "]\n",
    "\n",
    "for i, tailored_resume in enumerate(tailored_resumes, start=1):\n",
    "    file_path = os.path.join(output_directory, f\"tailored_resume_{i}.txt\")\n",
    "    with open(file_path, \"w\") as file:\n",
    "        file.write(tailored_resume)\n",
    "\n",
    "print(\"Files saved successfully!\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c959fa87-f5ff-4747-8e14-3ff27a1938f4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in c:\\users\\ash\\anaconda3\\lib\\site-packages (1.40.1)\n",
      "Requirement already satisfied: altair<6,>=4.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (5.4.1)\n",
      "Requirement already satisfied: blinker<2,>=1.0.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (1.8.2)\n",
      "Requirement already satisfied: cachetools<6,>=4.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (5.5.0)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (8.1.7)\n",
      "Requirement already satisfied: numpy<3,>=1.20 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (1.24.3)\n",
      "Requirement already satisfied: packaging<25,>=20 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (23.2)\n",
      "Requirement already satisfied: pandas<3,>=1.4.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (2.0.3)\n",
      "Requirement already satisfied: pillow<12,>=7.1.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (10.4.0)\n",
      "Requirement already satisfied: protobuf<6,>=3.20 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (5.29.0)\n",
      "Requirement already satisfied: pyarrow>=7.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (17.0.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (2.32.3)\n",
      "Requirement already satisfied: rich<14,>=10.14.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (13.9.4)\n",
      "Requirement already satisfied: tenacity<10,>=8.1.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (8.5.0)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (4.11.0)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (3.1.43)\n",
      "Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (0.9.1)\n",
      "Requirement already satisfied: tornado<7,>=6.0.3 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (6.4.1)\n",
      "Requirement already satisfied: watchdog<7,>=2.1.5 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from streamlit) (4.0.2)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (3.1.4)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (4.19.2)\n",
      "Requirement already satisfied: narwhals>=1.5.2 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from altair<6,>=4.0->streamlit) (1.15.2)\n",
      "Requirement already satisfied: colorama in c:\\users\\ash\\anaconda3\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.11)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2023.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.1)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)\n",
      "Requirement already satisfied: importlib-resources>=1.4.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (6.4.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)\n",
      "Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (1.3.10)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.16.0)\n",
      "Requirement already satisfied: zipp>=3.1.0 in c:\\users\\ash\\anaconda3\\lib\\site-packages (from importlib-resources>=1.4.0->jsonschema>=3.0->altair<6,>=4.0->streamlit) (3.17.0)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-12-04 13:08:43.058 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.787 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\Ash\\anaconda3\\lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2024-12-04 13:08:43.788 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.789 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.791 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.795 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.797 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.807 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.811 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.813 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.815 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.818 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.819 Session state does not function when running a script without `streamlit run`\n",
      "2024-12-04 13:08:43.822 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.823 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.829 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.832 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.835 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.837 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:08:43.839 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit\n",
    "# Streamlit GUI Example\n",
    "import streamlit as st\n",
    "\n",
    "st.title(\"Job Assistant: Tailored Resumes\")\n",
    "uploaded_file = st.file_uploader(\"Upload your resume\")\n",
    "job_links = st.text_area(\"Paste job links here (one per line)\")\n",
    "\n",
    "if st.button(\"Generate Tailored Resumes\"):\n",
    "    st.write(\"Processing your request...\")\n",
    "    # Call the workflow and display results\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "118f5e96-7313-419c-9657-76538af3cf3a",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-12-04 13:13:23.322 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:13:23.324 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:13:23.325 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2024-12-04 13:13:23.327 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "213bb39c-569f-44de-a7cf-3d1136b0c0ff",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import streamlit as st\n",
    "\n",
    "st.write(f\"Current Working Directory: {os.getcwd()}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
